### ISSUE TITLE
Unknown property: 'place-self'

### ISSUE THREAD

**Issue by bennypowers** [liuderchi/ide-css#50]
Given

```css
#submit {
  grid-column: 2/3;
  place-self: end;
}
```

ide-css reports: 

> Unknown property: 'place-self'

`place-self` is widely supported:

https://developer.mozilla.org/en-US/docs/Web/CSS/place-self

Please add it to ide-css.

Thanks for publishing this project.
